# Generated by Django 2.2.14 on 2020-11-05 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddingClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('isSMSsendingincluded', models.BooleanField()),
                ('office', models.IntegerField(max_length=4)),
                ('profile', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeCode', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('mark', models.CharField(max_length=20)),
                ('model', models.IntegerField(max_length=20)),
                ('modification', models.IntegerField(max_length=20)),
                ('licensePlate', models.CharField(max_length=20)),
                ('mileage', models.IntegerField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('adding_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AddingClient')),
            ],
        ),
        migrations.DeleteModel(
            name='Api',
        ),
    ]
