# Generated by Django 2.2.14 on 2020-11-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201105_0100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddingClient',
            new_name='Client',
        ),
    ]
