# Generated by Django 3.1.1 on 2020-11-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201105_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('normalized_manufacturer_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=64)),
                ('ARMTEC_code', models.CharField(max_length=20)),
                ('manufacturer_code', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('price_with_dot', models.FloatField(max_length=20)),
            ],
        ),
    ]
