# Generated by Django 3.1.1 on 2020-11-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201121_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
