# Generated by Django 3.1.1 on 2020-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_client_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('yearOfIssue', models.CharField(max_length=4)),
                ('modification', models.CharField(max_length=64)),
                ('mileage', models.IntegerField()),
                ('licensePlate', models.CharField(max_length=64)),
                ('typeCode', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GarageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_garage', models.IntegerField()),
                ('id_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='static/product_img/')),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='id_garage',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='modification',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='office',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.IntegerField(),
        ),
    ]
