# Generated by Django 3.1.1 on 2020-11-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201126_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GarageOrder',
            new_name='CarOrder',
        ),
        migrations.RenameField(
            model_name='carorder',
            old_name='id_garage',
            new_name='id_car',
        ),
        migrations.RenameField(
            model_name='garage',
            old_name='mileage',
            new_name='id_car',
        ),
        migrations.RemoveField(
            model_name='car',
            name='adding_client',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='code',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='licensePlate',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='model',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='modification',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='typeCode',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='yearOfIssue',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='brand', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='yearOfIssue',
            field=models.CharField(default=2020, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='id_garage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='licensePlate',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='modification',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='typeCode',
            field=models.CharField(max_length=10),
        ),
    ]
