# Generated by Django 3.1.1 on 2020-11-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_provider_providerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='has_error',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
