# Generated by Django 3.1.1 on 2020-11-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='manufacturer_code',
        ),
    ]
