# Generated by Django 3.1.1 on 2020-11-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20201127_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provider', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('vendor_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ARMTEC_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='normalized_manufacturer_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_with_dot',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='mail_for_reception',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_file',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='number_availability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='number_brand',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='number_description',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='number_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='number_vendor_code',
            field=models.IntegerField(null=True),
        ),
    ]
